CREATE DATABASE NurDB;

USE NurDB;

CREATE TABLE prayers(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prayer_name VARCHAR(25) NOT NULL,
    prayer_rakaa INT UNSIGNED NOT NULL,
    prayed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)ENGINE=InnoDB;

CREATE TABLE recites(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    page_from INT UNSIGNED NOT NULL,
    page_to INT UNSIGNED NOT NULL,
    recited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)ENGINE=InnoDb;
